[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra"
    ]

testpaths = "tests"

pythonpath = "src"

markers = [
    "smoke: quick test of major parts",
    "bugs: tests that reproduce issues",
    "slow: avoid these if in a hurry"
]

